### ISSUE TITLE
Promise 添加状态机的问题

### ISSUE THREAD

**Issue by a-meng** [panyifei/learning#1]
//Promise 添加状态机的问题
function resolve(){
    state = "fulfilled";
    setTimeout(function(){
      doneList.forEach(function(fulfill){
        fulfill();
      });
    },0);
  }
  fn(resolve);
//这段代码 在 new Promise就会执行，state就等于 ‘fulfilled’了 ;

setTimeout(function(){
      function resolve(){
         state = "fulfilled";
         doneList.forEach(function(fulfill){
           fulfill();
         });
      }
      fn(resolve);
 },0);

//是不是应该这样写？

**Comment by panyifei** [comment]
哈，你好，new Promise的时候不会执行resolve啊。

new Promise的时候只会执行fn，什么时候执行resolve是使用者定义在fn里的。

执行resolve的时候才会把state转化为fullfill的。

**Comment by Dragon-Rider** [comment]
这个repository写的很好赞一个~
